# Generated by Django 3.2.16 on 2023-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=50)),
                ('Item_slug', models.IntegerField()),
                ('Item_desc', models.TextField(max_length=150)),
                ('Item_price', models.IntegerField()),
                ('Item_stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('Item_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
