# Generated by Django 3.2.16 on 2023-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230116_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
