# Generated by Django 3.2.16 on 2023-01-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230116_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Item_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
            preserve_default=False,
        ),
    ]
