# Generated by Django 3.2.16 on 2023-01-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_items_item_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_qty', models.IntegerField()),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.CharField(max_length=4)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.items')),
            ],
        ),
    ]
