# Generated by Django 3.2.16 on 2023-01-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ShopUser',
        ),
    ]
