# Generated by Django 3.2.16 on 2023-01-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_user_shopuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
